// Lote autoral temático. Cada item: enunciado, resposta, quatro distratores, explicação.
// Não reproduz questões oficiais. Referências e revisão em docs/ENEM-TOPICOS.md.
export const blocos = [];
const sala=(id,materia,assunto,itens)=>blocos.push({id,materia,assunto,itens});

sala('porcentagem','matematica','Porcentagem',[
['Um tênis de R$ 320 recebe desconto de 15%. Quanto o comprador paga?', 'R$ 272',['R$ 48','R$ 305','R$ 280','R$ 368'],'O desconto é 320×0,15=48. O pagamento é 320−48=272 reais.'],
['Uma mensalidade passou de R$ 80 para R$ 92. Qual foi o aumento percentual em relação ao valor antigo?', '15%',['12%','13,04%','20%','115%'],'O acréscimo é 12 reais. Dividindo pela base antiga: 12/80=0,15=15%.'],
['Após um desconto de 20%, uma mochila custa R$ 144. Qual era o preço antes do desconto?', 'R$ 180',['R$ 164','R$ 172,80','R$ 115,20','R$ 720'],'144 representa 80% do preço original. Portanto, preço original=144/0,8=180.'],
['Uma loja aumenta um preço de R$ 100 em 10% e depois reduz o novo preço em 10%. Qual é o preço final?', 'R$ 99',['R$ 100','R$ 90','R$ 101','R$ 110'],'100×1,10×0,90=99. As porcentagens incidem sobre bases diferentes e não se anulam.'],
['Em uma turma de 240 estudantes, 35% usam bicicleta. Quantos estudantes usam bicicleta?', '84',['35','72','156','205'],'35% de 240 é 0,35×240=84 estudantes.']
]);
sala('funcao_afim','matematica','Função afim',[
['Um serviço cobra R$ 8 de taxa fixa e R$ 2 por quilômetro. Qual função representa o custo C de x quilômetros?', 'C(x)=8+2x',['C(x)=10x','C(x)=8x+2','C(x)=8−2x','C(x)=16x'],'A taxa fixa independe de x e entra como termo constante. O custo por quilômetro multiplica a distância.'],
['Um reservatório contém 500 litros e perde 20 litros por minuto a vazão constante. Quantos litros restam após 12 minutos?', '260 L',['240 L','480 L','740 L','25 L'],'V(t)=500−20t. Para t=12, V=500−240=260 litros, antes do esvaziamento.'],
['O plano A de impressão cobra R$ 30 mais R$ 0,20 por página. O plano B cobra R$ 10 mais R$ 0,40 por página. Em quantas páginas os custos se igualam?', '100 páginas',['50 páginas','20 páginas','200 páginas','150 páginas'],'30+0,2x=10+0,4x implica 20=0,2x, logo x=100. Ambos custam 50 reais nesse ponto.'],
['Uma reta passa pelos pontos (2,7) e (5,16). Qual é seu coeficiente angular?', '3',['9','5','1/3','23/7'],'A taxa de variação é (16−7)/(5−2)=9/3=3.'],
['Uma fábrica tem custo C(x)=200+5x e receita R(x)=9x, em reais. A partir de qual quantidade inteira vendida a receita supera o custo?', '51 unidades',['50 unidades','40 unidades','25 unidades','200 unidades'],'9x>200+5x resulta em x>50. Em 50 há equilíbrio; o primeiro inteiro com lucro é 51.']
]);
sala('probabilidade','matematica','Probabilidade',[
['Um dado comum honesto é lançado uma vez. Qual é a probabilidade de sair um número maior que 4?', '1/3',['1/6','1/2','2/3','5/6'],'Os resultados favoráveis são 5 e 6: dois entre seis igualmente prováveis, ou 2/6=1/3.'],
['Duas moedas honestas são lançadas de forma independente. Qual é a probabilidade de sair exatamente uma cara?', '1/2',['1/4','3/4','1','0'],'Os resultados equiprováveis são cara-cara, cara-coroa, coroa-cara e coroa-coroa. Dois têm exatamente uma cara.'],
['Uma urna contém 4 bolas verdes e 6 amarelas. Uma bola é retirada, devolvida e outra é retirada, sempre ao acaso. Qual é a probabilidade de duas verdes?', '4/25',['2/5','2/15','3/10','8/25'],'Com reposição, cada retirada tem probabilidade 4/10. O produto é 16/100=4/25.'],
['De 30 alunos, 18 estudam inglês, 12 estudam espanhol e 5 estudam ambos. Escolhendo um aluno ao acaso, qual a probabilidade de ele estudar pelo menos um desses idiomas?', '5/6',['1','1/6','3/5','2/5'],'A união contém 18+12−5=25 alunos. A probabilidade é 25/30=5/6.'],
['Em uma caixa há 5 peças boas e 1 defeituosa. Duas são retiradas ao acaso, sem reposição. Qual é a probabilidade de ambas serem boas?', '2/3',['25/36','5/6','1/3','1/6'],'A primeira ser boa tem chance 5/6. Depois restam 4 boas em 5: (5/6)×(4/5)=2/3.']
]);
sala('estatistica','matematica','Estatística',[
['Cinco entregas duraram 10, 12, 14, 14 e 20 minutos. Qual é a média aritmética dessas durações?', '14 minutos',['12 minutos','15 minutos','20 minutos','70 minutos'],'A soma é 70. Dividindo pelas cinco observações, a média é 14.'],
['Os salários de quatro funcionários são R$ 1500, R$ 1800, R$ 2200 e R$ 8000. Qual é a mediana?', 'R$ 2000',['R$ 3375','R$ 1800','R$ 2200','R$ 6500'],'Com quatro valores ordenados, a mediana é a média dos dois centrais: (1800+2200)/2=2000.'],
['Uma pesquisa registrou as quantidades de livros lidos: 0, 1, 1, 2, 3, 3, 3, 5. Qual é a moda?', '3',['1','2','2,25','5'],'Moda é o valor mais frequente. O número 3 aparece três vezes, mais que os demais.'],
['Duas turmas têm a mesma média em uma prova. A turma A apresenta desvio padrão menor que a B. Isso indica que, em A, as notas:', 'Estão menos dispersas em torno da média.',['São todas necessariamente iguais.','São obrigatoriamente maiores que em B.','Têm média diferente da informada.','Não podem incluir notas baixas.'],'O desvio padrão mede dispersão. Um valor menor não implica igualdade total nem média maior.'],
['Uma escola entrevista apenas alunos do clube de leitura para estimar o hábito de leitura de todos os estudantes. O principal problema é:', 'A amostra pode não representar o conjunto dos estudantes.',['Entrevistas nunca produzem dados.','Uma pesquisa exige entrevistar toda a população.','Os participantes não podem ler livros.','A quantidade de perguntas determina sozinha a representatividade.'],'Integrantes de um clube de leitura podem ter hábitos diferentes dos demais. O modo de seleção introduz possível viés.']
]);
sala('geometria_plana','matematica','Geometria plana',[
['Uma sala retangular mede 7 m por 4 m. Qual é o perímetro da sala?', '22 m',['28 m','11 m','14 m','56 m'],'O perímetro é a soma dos quatro lados: 2×(7+4)=22 m. 28 m² seria a área.'],
['Um canteiro triangular tem base 12 m e altura perpendicular de 5 m. Qual é a área?', '30 m²',['60 m²','17 m²','34 m²','120 m²'],'Área do triângulo=base×altura/2=12×5/2=30 m².'],
['Um terreno circular tem raio de 3 m. Adotando π=3, qual é sua área?', '27 m²',['9 m²','18 m²','54 m²','81 m²'],'A=πr²=3×3²=27 m². A expressão 2πr calcula o comprimento da circunferência.'],
['Uma escada de 5 m encosta em uma parede perpendicular ao chão. Sua base está a 3 m da parede. A que altura chega o topo?', '4 m',['2 m','3 m','8 m','√34 m'],'No triângulo retângulo, h²+3²=5². Logo h²=16 e h=4 m.'],
['Uma planta baixa é ampliada mantendo a semelhança, com todos os comprimentos multiplicados por 3. As áreas são multiplicadas por:', '9',['3','6','12','27'],'Área envolve duas dimensões lineares. O fator de ampliação é 3²=9.']
]);
sala('razao_proporcao','matematica','Razão e proporção',[
['Três torneiras idênticas enchem um tanque em 8 horas. Seis dessas torneiras, com vazões constantes, levam quanto tempo para encher o mesmo tanque?', '4 horas',['16 horas','8 horas','2 horas','24 horas'],'Dobrar a vazão total reduz o tempo à metade, mantidas as condições: 8/2=4 horas.'],
['Um carro percorre 180 km com 15 L de combustível. Mantido o consumo por quilômetro, quantos litros são necessários para 300 km?', '25 L',['20 L','30 L','12 L','45 L'],'O rendimento é 180/15=12 km/L. Para 300 km: 300/12=25 L.'],
['Uma verba de R$ 600 é dividida entre dois projetos na razão 2:3. Quanto recebe o projeto com a maior parte?', 'R$ 360',['R$ 240','R$ 300','R$ 400','R$ 200'],'São cinco partes no total; cada parte vale 120 reais. A maior parcela é 3×120=360.'],
['Em um mapa de escala 1:200 000, a distância entre duas localidades mede 4 cm. A distância real representada é:', '8 km',['0,8 km','80 km','800 km','2 km'],'4×200000=800000 cm, ou 8000 m, equivalentes a 8 km.'],
['Uma bebida usa 2 partes de concentrado para 5 partes de água. Para preparar 1,4 L da mistura, qual volume de concentrado é necessário?', '0,4 L',['0,56 L','0,7 L','1 L','0,2 L'],'A mistura tem sete partes. Cada uma vale 1,4/7=0,2 L. Duas partes são 0,4 L.']
]);

sala('cinematica','fisica','Cinemática',[
['Um ônibus percorre 90 km em 1,5 hora, sem contar outros trechos. Qual é sua velocidade média nesse percurso?', '60 km/h',['45 km/h','90 km/h','135 km/h','15 km/h'],'Velocidade média no percurso=90/1,5=60 km/h.'],
['Um carro se move a 72 km/h. Qual é essa velocidade em metros por segundo?', '20 m/s',['2 m/s','36 m/s','72 m/s','259,2 m/s'],'Para converter km/h em m/s, divide-se por 3,6. Assim, 72/3,6=20.'],
['Um móvel parte do repouso com aceleração constante de 2 m/s². Qual é sua velocidade após 6 s?', '12 m/s',['3 m/s','6 m/s','36 m/s','72 m/s'],'A aceleração acrescenta 2 m/s a cada segundo. Usando v=v₀+at, obtemos 0+2×6=12 m/s.'],
['Uma bicicleta mantém velocidade constante de 5 m/s durante 40 s em linha reta. Qual distância percorre?', '200 m',['8 m','45 m','160 m','400 m'],'Para velocidade constante, d=vt=5×40=200 m.'],
['Um estudante caminha 300 m para leste e depois 300 m para oeste, retornando ao ponto inicial. Seu deslocamento total é:', '0 m',['300 m para leste','600 m para oeste','600 m para leste','300 m para oeste'],'Deslocamento depende das posições inicial e final, que coincidem. A distância percorrida é 600 m, mas o deslocamento é zero.']
]);
sala('calorimetria','fisica','Calorimetria',[
['Uma amostra de 200 g de água recebe 8400 J. Usando calor específico de 4,2 J/(g·°C), sem mudança de fase, qual é o aumento de temperatura?', '10 °C',['20 °C','42 °C','100 °C','0,1 °C'],'Q=mcΔT; ΔT=8400/(200×4,2)=10 °C.'],
['Dois corpos a temperaturas diferentes são colocados em contato térmico, isolados do ambiente. O calor flui espontaneamente:', 'Do corpo mais quente para o mais frio.',['Do corpo de maior massa para o de menor massa sempre.','Do mais frio para o mais quente sempre.','Em função apenas do volume de cada corpo.','Somente se ambos forem do mesmo material.'],'A diferença de temperatura determina o sentido espontâneo da transferência de calor, até o equilíbrio térmico.'],
['Durante a fusão de gelo puro a 0 °C, sob pressão constante de 1 atm, o sistema absorve calor. Enquanto coexistem gelo e água em equilíbrio, a temperatura:', 'Permanece em 0 °C.',['Sobe obrigatoriamente até 100 °C.','Cai continuamente.','Depende apenas da massa inicial.','Torna-se negativa após a primeira gota.'],'Na mudança de fase nessas condições, o calor absorvido é latente, e a temperatura permanece constante enquanto a fusão ocorre.'],
['Massas iguais de água a 20 °C e a 60 °C são misturadas num recipiente ideal isolado, de capacidade térmica desprezível. A temperatura final é:', '40 °C',['30 °C','50 °C','80 °C','20 °C'],'Com mesmo calor específico e massas iguais, o calor perdido por uma parcela é ganho pela outra. A temperatura final é (20+60)/2=40 °C.'],
['Um cabo de panela é feito de material com baixa condutividade térmica. A finalidade principal é:', 'Reduzir a transferência de calor por condução até a mão.',['Aumentar a temperatura de ebulição da água.','Eliminar toda forma de transferência de energia.','Produzir frio por reação nuclear.','Aumentar a condução para o usuário.'],'Materiais maus condutores dificultam a condução de calor. Não bloqueiam de modo absoluto todas as formas de troca térmica.']
]);
sala('eletricidade','fisica','Circuitos elétricos',[
['Um resistor de 30 Ω é submetido a uma tensão de 12 V. Qual corrente o atravessa?', '0,4 A',['2,5 A','360 A','18 A','42 A'],'Pela lei de Ohm, I=V/R=12/30=0,4 A.'],
['Dois resistores de 4 Ω e 6 Ω estão em série. Qual a resistência equivalente?', '10 Ω',['2 Ω','2,4 Ω','24 Ω','5 Ω'],'Na associação em série, somam-se as resistências: 4+6=10 Ω.'],
['Dois resistores iguais de 8 Ω são ligados em paralelo. Qual é a resistência equivalente?', '4 Ω',['16 Ω','8 Ω','64 Ω','2 Ω'],'Para dois resistores iguais em paralelo, a resistência equivalente é metade: 8/2=4 Ω.'],
['Um aparelho opera com tensão de 120 V e corrente de 2 A. Qual é sua potência elétrica?', '240 W',['60 W','122 W','118 W','0,0167 W'],'A potência elétrica é o produto da tensão pela corrente: P=VI=120×2=240 W, equivalente a 240 joules por segundo.'],
['As lâmpadas de uma instalação são ligadas em paralelo a uma fonte ideal. Uma delas queima e abre seu ramo. Nas demais lâmpadas:', 'A tensão da fonte continua aplicada aos seus ramos.',['A corrente obrigatoriamente se torna zero.','Todas queimam necessariamente ao mesmo tempo.','As resistências passam a estar em série.','A tensão precisa dobrar.'],'Ramos paralelos têm conexão independente com a fonte. A abertura de um ramo não interrompe, por si só, os demais.']
]);
sala('ondulatoria','fisica','Ondulatória',[
['Uma onda tem frequência de 50 Hz e comprimento de onda de 2 m. Qual é sua velocidade de propagação?', '100 m/s',['25 m/s','52 m/s','0,04 m/s','2500 m/s'],'A velocidade de propagação é o produto do comprimento de onda pela frequência: v=λf=2×50=100 m/s.'],
['Uma onda realiza 5 oscilações por segundo. Qual é seu período?', '0,2 s',['5 s','10 s','0,5 s','2 s'],'O período é o inverso da frequência: T=1/5=0,2 s.'],
['Uma pessoa distingue um som agudo de um grave principalmente pela diferença de:', 'Frequência.',['Velocidade da luz.','Temperatura do ouvido.','Cor do instrumento.','Distância obrigatória entre os ouvintes.'],'A altura sonora está associada à frequência: maior frequência corresponde a som mais agudo. Volume está ligado à intensidade.'],
['Um pulso sonoro retorna como eco 0,4 s após ser emitido. Se o som se propaga a 340 m/s, qual a distância até a parede refletora?', '68 m',['136 m','85 m','34 m','170 m'],'O intervalo inclui ida e volta. A distância até a parede é 340×0,4/2=68 m.'],
['Uma onda passa de um meio para outro, mantendo a mesma fonte oscilante. Se sua velocidade muda, qual grandeza permanece igual na passagem?', 'A frequência.',['O comprimento de onda obrigatoriamente.','A amplitude obrigatoriamente.','A velocidade obrigatoriamente.','A densidade dos meios.'],'A frequência é determinada pela fonte e se conserva na refração. Com v=λf, a mudança de velocidade altera o comprimento de onda.']
]);

sala('solucoes','quimica','Soluções e concentração',[
['Uma solução contém 15 g de soluto em volume final de 300 mL. Qual é a concentração em g/L?', '50 g/L',['5 g/L','45 g/L','0,05 g/L','20 g/L'],'Primeiro convertemos o volume: 300 mL=0,3 L. A concentração em massa por volume é C=15/0,3=50 g/L.'],
['Uma solução contém 0,2 mol de soluto em 0,5 L de solução. Qual é sua concentração molar?', '0,4 mol/L',['0,1 mol/L','2,5 mol/L','0,7 mol/L','4 mol/L'],'Concentração molar=n/V=0,2/0,5=0,4 mol/L.'],
['Uma amostra de 200 mL de solução 1,5 mol/L é diluída até 600 mL, sem perda de soluto. A concentração final é:', '0,5 mol/L',['4,5 mol/L','1,5 mol/L','0,375 mol/L','3 mol/L'],'C₁V₁=C₂V₂. C₂=1,5×200/600=0,5 mol/L.'],
['Uma mistura homogênea contém 20 g de açúcar dissolvidos em 180 g de água. Qual é a porcentagem em massa de açúcar na solução?', '10%',['11,11%','20%','90%','1%'],'A massa da solução é 200 g. A fração do açúcar é 20/200=0,1, ou 10%.'],
['Uma solução não saturada perde parte do solvente por evaporação, sem perder soluto nem formar precipitado. Sua concentração em massa por volume:', 'Aumenta.',['Diminui necessariamente.','Permanece sempre igual.','Torna-se zero.','Não depende do volume.'],'A massa de soluto permanece, enquanto o volume de solução diminui. O quociente massa/volume aumenta nas condições descritas.']
]);
sala('estequiometria','quimica','Estequiometria',[
['Na reação 2 H₂ + O₂ → 2 H₂O, quantos mols de O₂ são necessários para reagir completamente com 6 mol de H₂?', '3 mol',['6 mol','12 mol','2 mol','1 mol'],'A proporção é 2 mol H₂ para 1 mol O₂. Para 6 mol H₂ são necessários 3 mol O₂.'],
['Considere C + O₂ → CO₂. Com massas molares C=12 g/mol e CO₂=44 g/mol, qual massa de CO₂ é formada por 6 g de C, com O₂ em excesso?', '22 g',['6 g','12 g','44 g','88 g'],'6 g de C equivalem a 0,5 mol, produzindo 0,5 mol de CO₂. Massa=0,5×44=22 g.'],
['Uma reação deveria produzir 80 g de produto, mas foram obtidos 60 g. Qual é o rendimento percentual?', '75%',['20%','25%','60%','133,3%'],'Rendimento=produção obtida/teórica×100=60/80×100=75%.'],
['Na reação N₂ + 3 H₂ → 2 NH₃, misturam-se 2 mol de N₂ e 3 mol de H₂. Qual reagente limita a formação de amônia?', 'H₂',['N₂','NH₃','Ambos são consumidos integralmente.','Nenhum, porque há sempre excesso de ambos.'],'3 mol de H₂ reagem com somente 1 mol de N₂. O H₂ acaba primeiro e sobra 1 mol de N₂.'],
['Uma amostra de 50 g contém 80% em massa de um reagente puro e 20% de impurezas inertes. Qual massa do reagente está disponível para reagir?', '40 g',['10 g','50 g','62,5 g','80 g'],'A massa do reagente é 0,8×50=40 g; os 10 g restantes são impurezas.']
]);
sala('separacao_misturas','quimica','Separação de misturas',[
['Uma mistura contém areia e limalha de ferro. Qual método separa diretamente o ferro usando sua resposta a um campo magnético?', 'Separação magnética.',['Filtração simples.','Destilação fracionada.','Evaporação.','Cromatografia.'],'Um ímã atrai a limalha de ferro, permitindo separá-la da areia nas condições usuais.'],
['Óleo e água formam duas camadas após repouso. Qual técnica é adequada para separá-los em laboratório?', 'Decantação em funil de separação.',['Peneiração.','Fusão.','Filtração em papel comum como etapa única.','Sublimação.'],'São líquidos imiscíveis com densidades diferentes. O funil de separação permite escoar a camada inferior de maneira controlada.'],
['Para recuperar água líquida de uma solução de sal não volátil, pode-se aquecer e condensar o vapor produzido. Esse processo é:', 'Destilação simples.',['Peneiração.','Imantação.','Catação.','Dissolução fracionada.'],'A destilação vaporiza o solvente e depois o condensa. O sal não volátil permanece no recipiente de aquecimento.'],
['Uma mistura de grãos grandes e areia seca pode ser separada aproveitando a diferença de tamanho das partículas. O método é:', 'Peneiração.',['Destilação.','Centrifugação obrigatoriamente.','Eletrólise.','Condensação.'],'A peneira retém as partículas maiores e permite a passagem das menores. O processo usa diferença de tamanho.'],
['No tratamento de uma suspensão, a centrifugação acelera a separação que, em repouso, poderia ocorrer lentamente por sedimentação. Ela se baseia principalmente em:', 'Diferenças de comportamento das partículas sob rotação, relacionadas à densidade e ao tamanho.',['Transformar todos os sólidos em gases.','Alterar o número de prótons dos elementos.','Destruir quimicamente o líquido.','Tornar todos os componentes igualmente solúveis.'],'A rotação acelera a deposição de partículas suspensas; tamanho, densidade e propriedades do meio influenciam a separação.']
]);
sala('quimica_organica','quimica','Funções orgânicas',[
['O etanol, CH₃CH₂OH, apresenta qual função orgânica?', 'Álcool.',['Aldeído.','Cetona.','Ácido carboxílico.','Éster.'],'A hidroxila está ligada a carbono saturado, caracterizando um álcool.'],
['O ácido etanoico, CH₃COOH, presente em soluções de vinagre, tem como grupo característico:', 'Carboxila.',['Hidroxila de álcool apenas.','Grupo amino.','Ligação tripla carbono-carbono.','Anel aromático.'],'O grupo −COOH é a carboxila, que caracteriza os ácidos carboxílicos.'],
['A propanona, CH₃COCH₃, possui um grupo carbonila entre dois carbonos. Ela pertence à função:', 'Cetona.',['Álcool.','Amina.','Éter.','Aldeído.'],'Cetonas têm carbonila ligada a dois grupos carbônicos. No aldeído, a carbonila possui ao menos um hidrogênio ligado ao carbono carbonílico.'],
['Um composto apresenta a estrutura CH₃CH₂OCH₂CH₃. A função orgânica é:', 'Éter.',['Éster.','Álcool.','Ácido carboxílico.','Cetona.'],'O oxigênio está entre dois grupos carbônicos, sem carbonila próxima: estrutura R−O−R, típica de éter.'],
['A reação entre um ácido carboxílico e um álcool pode formar um éster e água. Esse processo recebe o nome de:', 'Esterificação.',['Hidrogenação.','Saponificação do éster.','Combustão completa.','Polimerização por adição.'],'Na esterificação, ácido carboxílico e álcool formam éster e água. Saponificação é uma hidrólise básica de éster.']
]);
sala('ecologia','biologia','Ecologia',[
['Em um lago, algas são consumidas por pequenos crustáceos, que alimentam peixes. Os crustáceos são:', 'Consumidores primários.',['Produtores.','Consumidores terciários.','Autótrofos.','Fatores abióticos.'],'Ao consumir produtores como as algas, os crustáceos ocupam o nível de consumidores primários nessa cadeia.'],
['Duas espécies disputam um recurso alimentar limitado no mesmo ambiente. A interação descrita é:', 'Competição interespecífica.',['Mutualismo obrigatório.','Comensalismo.','Cooperação sem custos.','Parasitismo obrigatório.'],'A disputa por recursos entre espécies diferentes caracteriza competição interespecífica, com possíveis efeitos negativos para ambas.'],
['Fungos e bactérias decompõem restos de seres vivos. Uma consequência ecológica fundamental desse processo é:', 'A devolução de nutrientes ao ambiente.',['A criação de energia a partir do nada.','O desaparecimento dos ciclos da matéria.','A conversão de todos os decompositores em produtores.','A interrupção obrigatória da fotossíntese.'],'Decompositores transformam matéria orgânica e contribuem para a reciclagem de nutrientes. A energia não é reciclada como a matéria.'],
['Após um incêndio que preservou parte do solo e sementes, a vegetação começa a se restabelecer. Esse processo é exemplo de:', 'Sucessão ecológica secundária.',['Sucessão primária em rocha nua sem solo.','Ausência de sucessão.','Extinção de toda forma de vida no planeta.','Transformação imediata em comunidade estável.'],'A sucessão secundária ocorre em área previamente ocupada, com solo e possíveis propágulos remanescentes.'],
['Um poluente persistente acumula-se em organismos e apresenta concentrações maiores nos predadores de topo. Esse aumento ao longo dos níveis tróficos é chamado de:', 'Biomagnificação.',['Fotossíntese.','Fixação de nitrogênio.','Sucessão primária.','Osmose reversa.'],'Biomagnificação é o aumento da concentração de certos contaminantes ao longo da cadeia alimentar, especialmente quando persistentes e pouco eliminados.']
]);
sala('genetica','biologia','Genética mendeliana',[
['Em uma característica com dominância completa, A é dominante sobre a. Qual cruzamento produz apenas descendentes Aa?', 'AA × aa',['Aa × Aa','Aa × aa','AA × Aa','aa × aa'],'O genitor AA só fornece A e o genitor aa só fornece a. Todos os descendentes serão Aa.'],
['No cruzamento Aa × aa, sob segregação mendeliana, qual a probabilidade de um descendente ser aa?', '50%',['25%','75%','100%','0%'],'O heterozigoto produz A ou a com igual chance; o recessivo só produz a. Metade dos descendentes esperados será aa.'],
['Um indivíduo possui genótipo Bb em determinado gene. O termo que descreve esse genótipo é:', 'Heterozigoto.',['Homozigoto dominante.','Homozigoto recessivo.','Haploide necessariamente.','Clonal necessariamente.'],'Há dois alelos diferentes para o gene, B e b, caracterizando heterozigose.'],
['Num caráter autossômico recessivo com penetrância completa, dois pais de fenótipo dominante têm um filho recessivo. Nesse modelo, ambos os pais devem ser:', 'Heterozigotos.',['Homozigotos dominantes.','Homozigotos recessivos.','Portadores apenas do alelo dominante.','Incapazes de transmitir o alelo recessivo.'],'O filho aa recebe um a de cada genitor. Como ambos manifestam o fenótipo dominante, são Aa no modelo indicado.'],
['No cruzamento Aa × Aa, cada filho tem probabilidade de 1/4 de ser aa. Se o primeiro filho foi aa, qual é a probabilidade de o segundo também ser aa?', '1/4',['1/16','1/2','3/4','0'],'Os eventos reprodutivos são independentes no modelo. Saber o resultado do primeiro não altera a chance do segundo. 1/16 seria a chance conjunta de dois aa antes de conhecer ambos os resultados.']
]);
sala('citologia','biologia','Citologia',[
['Qual estrutura celular atua diretamente na síntese de proteínas, estando presente em células procarióticas e eucarióticas?', 'Ribossomo.',['Cloroplasto.','Lisossomo.','Complexo golgiense.','Núcleo delimitado por membrana.'],'Ribossomos realizam tradução do RNA mensageiro e estão presentes nos dois tipos celulares.'],
['Uma célula perde água quando colocada em uma solução hipertônica em relação ao seu interior. O processo principal de passagem da água é:', 'Osmose.',['Tradução.','Replicação.','Exocitose obrigatória.','Fagocitose.'],'Osmose é o movimento de água através de membrana seletivamente permeável, favorecendo o lado com maior concentração efetiva de solutos.'],
['Em células eucarióticas, qual organela está associada à maior parte da produção de ATP por respiração aeróbia?', 'Mitocôndria.',['Vacúolo contrátil.','Nucléolo.','Complexo golgiense.','Centríolo.'],'A cadeia respiratória e a fosforilação oxidativa ocorrem na membrana interna mitocondrial. A glicólise ocorre no citosol.'],
['A membrana plasmática é descrita como seletivamente permeável porque:', 'Controla a passagem de substâncias entre célula e meio.',['Impede absolutamente qualquer passagem.','É feita apenas de DNA.','Permite a passagem idêntica de todas as moléculas.','Só existe em células animais.'],'A bicamada lipídica e suas proteínas condicionam a passagem de substâncias por diferentes mecanismos.'],
['Uma característica que distingue células procarióticas das eucarióticas é que as procarióticas:', 'Não possuem núcleo delimitado por envoltório nuclear.',['Não possuem material genético.','Não possuem membrana plasmática.','Não realizam metabolismo.','Possuem obrigatoriamente cloroplastos.'],'Procariontes têm DNA em uma região chamada nucleoide, sem envoltório nuclear, mas possuem membrana e metabolismo.']
]);
sala('fotossintese','biologia','Fotossíntese',[
['Na fotossíntese de plantas, a energia luminosa é transformada principalmente em:', 'Energia química associada a compostos orgânicos.',['Átomos de carbono criados pela luz.','Energia nuclear.','Massa mineral sem reações químicas.','Som, como produto obrigatório.'],'A luz fornece energia para processos que permitem a síntese de matéria orgânica a partir de carbono inorgânico.'],
['O oxigênio molecular liberado na fotossíntese oxigênica provém diretamente da:', 'Água.',['Glicose absorvida pelas raízes.','Clorofila destruída.','Areia do solo.','Fixação do gás nitrogênio.'],'A oxidação da água nas reações fotoquímicas libera elétrons, prótons e O₂.'],
['Nas células vegetais, o ciclo de Calvin ocorre principalmente em qual região do cloroplasto?', 'Estroma.',['Matriz mitocondrial.','Nucléolo.','Membrana plasmática.','Interior dos lisossomos.'],'O estroma contém as enzimas do ciclo de Calvin, que utiliza ATP e NADPH na assimilação do carbono.'],
['Durante um período seco, o fechamento dos estômatos ajuda a reduzir a perda de água, mas pode limitar a fotossíntese porque:', 'Dificulta a entrada de CO₂.',['Cria cloroplastos extras automaticamente.','Impede toda respiração para sempre.','Aumenta obrigatoriamente a captação de CO₂.','Converte água diretamente em glicose sem carbono.'],'Os estômatos permitem trocas gasosas. Seu fechamento reduz transpiração, mas restringe a entrada de CO₂ necessário à fixação de carbono.'],
['Uma planta é mantida no escuro por algumas horas. Sobre seus processos energéticos, é correto afirmar que:', 'A respiração celular pode continuar utilizando reservas orgânicas.',['A respiração depende diretamente da luz em todas as etapas.','A planta deixa de consumir qualquer substância.','A fotossíntese libera mais oxigênio no escuro.','As mitocôndrias desaparecem imediatamente.'],'A respiração celular não exige iluminação e pode usar compostos armazenados. A planta não realiza apenas fotossíntese.']
]);

sala('interpretacao','portugues','Interpretação de texto',[
['Leia o trecho autoral: “A cidade inaugurou uma biblioteca. As portas estavam abertas, mas o horário coincidia com o trabalho de quase todos.” A ressalva sugere que:', 'A existência do espaço não garante, sozinha, acesso efetivo.',['Nenhum morador gosta de ler.','Bibliotecas devem funcionar somente de madrugada.','A inauguração não ocorreu.','O texto trata apenas da arquitetura.'],'O contraste entre portas abertas e incompatibilidade de horários problematiza as condições de acesso, não o interesse pela leitura.'],
['Em um relato fictício, lê-se: “Guardei o relógio na gaveta. Naquele domingo, queria ouvir o tempo passar pelas conversas.” A expressão final valoriza:', 'A experiência de convivência sem a preocupação constante com o relógio.',['A capacidade literal de ouvir ponteiros a quilômetros.','A rejeição a qualquer conversa.','A necessidade de consertar o relógio.','A medição científica da velocidade do som.'],'A expressão é figurada e relaciona a passagem do tempo às conversas, em contraste com sua medição pelo relógio.'],
['Um texto informa que uma pesquisa entrevistou 100 usuários de uma praça e que 70 pediram mais árvores. Qual conclusão é sustentada diretamente pelo dado?', '70% dos entrevistados pediram mais árvores.',['70% de toda a cidade pediram mais árvores.','Todos os usuários rejeitam árvores.','O plantio já foi realizado.','A pesquisa prova que árvores eliminam qualquer problema urbano.'],'70 de 100 corresponde a 70% daquela amostra. Sem outras informações, não se deve generalizar para toda a cidade ou afirmar execução da proposta.'],
['Leia o aviso fictício: “A água que você economiza hoje também faz falta amanhã.” O objetivo principal do aviso é:', 'Incentivar o uso responsável da água pensando no futuro.',['Ensinar uma fórmula química.','Anunciar que a água não é necessária.','Defender o desperdício imediato.','Informar o preço exato da conta.'],'O aviso associa a ação presente às necessidades futuras para orientar uma atitude de conservação.'],
['Em uma resenha, a autora escreve: “O filme tem belas imagens, embora o roteiro deixe perguntas importantes sem resposta.” A avaliação é:', 'Mista: reconhece uma qualidade e aponta uma limitação.',['Inteiramente positiva e sem ressalvas.','Inteiramente negativa e sem elogios.','Uma descrição sem opinião.','Uma prova de que o filme não foi visto.'],'“Belas imagens” é elogio e “embora” introduz a ressalva sobre o roteiro. O trecho combina apreciações distintas.']
]);
sala('coesao','portugues','Coesão textual',[
['No trecho “Choveu intensamente; por isso, o passeio foi adiado”, a expressão “por isso” introduz:', 'Uma consequência.',['Uma condição.','Uma comparação.','Uma oposição.','Uma finalidade.'],'O adiamento é apresentado como consequência da chuva. A expressão conecta causa anteriormente indicada ao efeito.'],
['Em “Embora estivesse cansada, a estudante concluiu a leitura”, a oração iniciada por “embora” expressa:', 'Concessão.',['Finalidade.','Comparação.','Consequência necessária.','Tempo futuro.'],'A concessão apresenta uma circunstância que poderia dificultar a ação, mas não a impediu.'],
['Leia: “O museu recebeu novos documentos. Eles serão digitalizados no próximo mês.” O pronome “eles” retoma:', 'Novos documentos.',['O museu.','O próximo mês.','Os visitantes não mencionados.','Os computadores não mencionados.'],'O pronome plural masculino retoma o antecedente “novos documentos”, evitando repetição.'],
['Em “Estude os gráficos para que possa comparar os resultados”, a expressão “para que” indica:', 'Finalidade.',['Contradição.','Concessão.','Causa já concluída.','Alternância.'],'Comparar os resultados é a finalidade atribuída ao estudo dos gráficos.'],
['Qual substituição preserva o sentido de contraste em “O projeto é viável; contudo, exige planejamento”?', '“O projeto é viável; porém, exige planejamento.”',['“O projeto é viável; portanto, exige planejamento.”','“O projeto é viável; porque exige planejamento.”','“O projeto é viável; logo, exige planejamento.”','“O projeto é viável; por isso, exige planejamento.”'],'“Contudo” e “porém” são conectores adversativos. “Portanto”, “logo” e “por isso” indicam conclusão ou consequência; “porque” introduz causa ou explicação.']
]);
sala('variacao_linguistica','portugues','Variação linguística',[
['Um documentário preserva a maneira de falar de moradores de diferentes regiões. Essa escolha pode contribuir para:', 'Reconhecer a diversidade linguística e cultural.',['Demonstrar que só uma região possui língua legítima.','Eliminar todas as diferenças de pronúncia.','Provar incapacidade intelectual de falantes.','Substituir a fala de todos por uma única variedade.'],'Variedades regionais integram a diversidade da língua e podem expressar identidades. Diferenças não indicam inferioridade dos falantes.'],
['Uma profissional usa linguagem técnica com colegas e explica o mesmo tema com palavras comuns ao público. Essa mudança exemplifica:', 'Adequação da linguagem ao interlocutor e à situação.',['Ausência de domínio linguístico necessariamente.','Proibição do uso de termos técnicos.','Mudança obrigatória de idioma.','Incapacidade de explicar o assunto.'],'A escolha do registro considera público e finalidade. Adaptar a linguagem pode facilitar a compreensão.'],
['Quando alguém ridiculariza a pronúncia regional de outra pessoa e a associa à falta de inteligência, pratica:', 'Preconceito linguístico.',['Análise neutra de uma equação.','Tradução simultânea.','Revisão de dados estatísticos.','Classificação biológica.'],'O julgamento transforma uma diferença linguística em inferiorização social do falante, caracterizando preconceito linguístico.'],
['Expressões comuns em cartas do século XIX podem ser pouco usadas hoje. Essa diferença exemplifica variação:', 'Histórica.',['Apenas geográfica, sem relação com o tempo.','Exclusivamente individual e sem contexto.','Biológica.','Inexistente, pois línguas não mudam.'],'Mudanças no uso da língua ao longo do tempo correspondem à variação histórica ou diacrônica.'],
['No ensino da língua, trabalhar a norma-padrão e reconhecer variedades populares são ações:', 'Compatíveis, pois ampliam repertório sem desvalorizar os falantes.',['Incompatíveis em qualquer contexto.','Que exigem abandonar a leitura.','Que provam que só a fala formal comunica.','Que eliminam a necessidade de adequação.'],'Ensinar usos formais pode ampliar possibilidades de participação, ao mesmo tempo que se reconhece a legitimidade de outras variedades.']
]);
sala('cartografia','humanas','Cartografia',[
['Em um mapa convencional com o norte no alto, um ponto localizado diretamente à esquerda de outro fica a:', 'Oeste.',['Leste.','Norte.','Sul.','Nordeste.'],'Com norte no alto, leste fica à direita e oeste à esquerda.'],
['Um mapa de escala 1:25 000 representa 1 cm no papel como qual distância real?', '250 m',['25 m','25 km','2,5 m','250 km'],'25000 cm equivalem a 250 m, dividindo-se por 100.'],
['Linhas de latitude indicam posições em relação à:', 'Linha do Equador.',['Linha internacional de data exclusivamente.','Altitude do relevo.','Distância ao centro da Terra.','Velocidade de rotação.'],'Latitude é a distância angular ao Equador, medida para norte ou sul.'],
['Em um mapa topográfico, curvas de nível muito próximas indicam, em geral:', 'Maior declividade do terreno.',['Terreno necessariamente plano.','Ausência de variação de altitude.','Maior distância vertical entre quaisquer curvas por definição.','Que o mapa não possui escala.'],'Para a mesma equidistância vertical entre curvas, menor separação horizontal significa variação de altitude mais rápida e maior declividade.'],
['Ao transformar a superfície curva da Terra em um mapa plano, as projeções cartográficas:', 'Produzem distorções, priorizando determinadas propriedades.',['Preservam sempre todas as áreas, formas e distâncias.','Eliminam a necessidade de escala.','Mostram obrigatoriamente apenas um país.','Impedem qualquer uso de coordenadas.'],'Nenhuma projeção plana preserva simultaneamente todas as propriedades da superfície terrestre. A escolha depende da finalidade do mapa.']
]);
sala('urbanizacao','humanas','Urbanização',[
['A substituição de solo vegetado por asfalto em uma bacia urbana tende a:', 'Aumentar o escoamento superficial e reduzir a infiltração.',['Aumentar obrigatoriamente a infiltração.','Eliminar todas as enchentes.','Reduzir a água escoada em qualquer chuva.','Impedir a precipitação.'],'Superfícies impermeáveis dificultam infiltração e favorecem escoamento, podendo agravar alagamentos conforme drenagem e chuva.'],
['Moradores vivem em um município e viajam diariamente para trabalhar em outro, voltando ao fim do dia. Esse padrão é conhecido como:', 'Movimento pendular.',['Êxodo rural necessariamente.','Migração definitiva internacional.','Transumância de rebanhos.','Nomadismo sem residência fixa.'],'Movimento pendular envolve deslocamentos regulares entre residência e trabalho ou estudo, sem mudança definitiva de moradia.'],
['Áreas centrais densamente construídas podem apresentar temperaturas superiores às de áreas vegetadas próximas. Esse fenômeno é:', 'Ilha de calor urbana.',['Inversão dos polos magnéticos.','Maré oceânica.','Glaciação urbana.','Tsunami térmico.'],'Materiais urbanos, menor vegetação e fontes de calor alteram o balanço de energia e favorecem temperaturas locais mais altas.'],
['Uma política habitacional instala moradias longe de emprego, escola e transporte. Mesmo oferecendo casas, ela pode ampliar:', 'Dificuldades de acesso e segregação socioespacial.',['A proximidade automática entre todos os serviços.','A mobilidade gratuita universal.','A integração urbana em qualquer circunstância.','A eliminação dos custos de deslocamento.'],'Moradia precisa ser articulada a infraestrutura e serviços. Localização isolada pode reproduzir desigualdade territorial.'],
['Uma cidade prioriza corredores de ônibus e calçadas acessíveis. A medida busca principalmente:', 'Melhorar a mobilidade e o acesso por transporte coletivo e deslocamento a pé.',['Impedir toda circulação de pessoas.','Aumentar necessariamente o número de carros por habitante.','Eliminar a necessidade de planejamento.','Garantir que todos percorram a mesma distância.'],'A infraestrutura pode tornar viagens coletivas e a pé mais acessíveis e eficientes, sem prometer resolver todos os problemas de circulação.']
]);
sala('revolucao_industrial','humanas','Revolução Industrial',[
['Uma mudança associada à industrialização foi a concentração de máquinas e trabalhadores em fábricas. Isso favoreceu:', 'Maior controle dos horários e das etapas da produção pelo empregador.',['O domínio integral do processo por todo trabalhador necessariamente.','O desaparecimento de relações de trabalho.','A eliminação da divisão de tarefas.','A independência total entre etapas produtivas.'],'A organização fabril intensificou disciplina de tempo, supervisão e divisão de tarefas, em contraste com muitas formas artesanais.'],
['Na industrialização britânica, o carvão mineral teve papel importante por:', 'Fornecer energia para máquinas a vapor e processos industriais.',['Ser a única matéria-prima de tecidos de algodão.','Substituir a necessidade de qualquer transporte.','Ser uma fonte renovável de reposição rápida.','Eliminar a emissão de poluentes.'],'O carvão foi uma fonte energética decisiva para vapor e metalurgia. É combustível fóssil e seu uso não elimina poluição.'],
['A expansão das fábricas atraiu trabalhadores para centros urbanos. Entre os desafios sociais de muitas cidades industriais estavam:', 'Moradias precárias e insuficiência de saneamento.',['Ausência completa de trabalhadores.','Distribuição igualitária automática de renda.','Desaparecimento da demanda por moradia.','Fim imediato de todas as doenças.'],'O crescimento urbano frequentemente ocorreu sem infraestrutura suficiente, associado a precariedade habitacional e sanitária.'],
['A organização de trabalhadores em sindicatos relaciona-se historicamente à busca por:', 'Negociação coletiva de condições de trabalho e direitos.',['Proibição de toda ação coletiva.','Retorno obrigatório à servidão medieval.','Fim de qualquer reivindicação salarial.','Eliminação de toda legislação trabalhista por definição.'],'Sindicatos permitem organização e representação coletiva em demandas como salários, jornadas e condições de trabalho.'],
['Um texto histórico descreve produção em série e tarefas repetitivas distribuídas entre vários operários. O conceito mais diretamente relacionado é:', 'Divisão técnica do trabalho.',['Autossuficiência de cada trabalhador em todas as etapas.','Ausência de especialização.','Produção doméstica integral necessariamente.','Extinção da organização industrial.'],'A divisão técnica distribui operações produtivas entre trabalhadores e setores, especializando atividades e conectando etapas.']
]);

export function montarSalas() {
  return blocos.map((b,n)=>({id:b.id,materia:b.materia,nome:`${b.assunto} — ENEM`,questoes:b.itens.map(([enunciado,resposta,distratores,explicacao],i)=>{
    const correta_idx=(n+i)%5;
    const alternativas=[...distratores];alternativas.splice(correta_idx,0,resposta);
    return {assunto:b.assunto,enunciado,alternativas,correta_idx,explicacao};
  })}));
}
