// Questões autorais NIVORA. Não são itens oficiais nem previsão de prova.
// Fontes e critérios de revisão: docs/ENEM-CONTEUDO.md.
const q = (assunto, enunciado, alternativas, correta_idx, explicacao) => ({ assunto, enunciado, alternativas, correta_idx, explicacao });
export const salasEnem = [
 { id:'portugues', nome:'Português — ENEM', materia:'portugues', questoes:[
 q('Interpretação de texto','Em uma campanha fictícia de biblioteca, lê-se: “Leve um livro. Devolva uma ideia.” A segunda frase, associada à primeira, sugere que a leitura deve favorecer:', ['A devolução de um objeto diferente do emprestado.','A substituição dos livros por opiniões sem leitura.','A produção e a circulação de reflexões entre leitores.','A cobrança de uma taxa por cada empréstimo.','A proibição de discordar dos autores.'],2,'A campanha associa o empréstimo à elaboração de ideias. “Devolver uma ideia” tem sentido figurado: compartilhar reflexões, e não substituir materialmente o livro. Não há referência a taxa, censura ou abandono da leitura.'),
 q('Coesão textual','Leia o trecho autoral: “A cidade ampliou as ciclovias. Entretanto, faltam conexões entre os bairros.” A palavra “entretanto” estabelece entre as frases uma relação de:', ['Causa, pois as ciclovias provocaram a falta de conexão.','Conclusão, pois a segunda frase resume a primeira.','Tempo, pois indica quando ocorreu a ampliação.','Contraste, pois apresenta uma limitação do avanço mencionado.','Condição, pois a ampliação depende de uma hipótese.'],3,'“Entretanto” introduz oposição ou ressalva. A ampliação é um avanço, mas a ausência de conexões limita seu alcance. A relação não é temporal, condicional, causal ou conclusiva.'),
 q('Variação linguística','Em entrevista para um documentário sobre sua comunidade, uma moradora usa expressões regionais. A equipe decide preservar essas expressões, sem apresentá-las como erros. Essa decisão reconhece que:', ['As variedades regionais expressam identidades e são formas legítimas de uso da língua.','Uma língua possui apenas uma forma correta em qualquer situação.','A escrita formal deve reproduzir todas as características da fala.','Expressões regionais impedem necessariamente a comunicação.','A existência de variedades elimina a necessidade de adequação ao contexto.'],0,'Variações regionais fazem parte da diversidade linguística e podem marcar pertencimento. Reconhecer sua legitimidade não elimina a adequação ao contexto nem torna todas as situações comunicativas iguais.'),
 q('Argumentação','Um texto autoral defende ampliar o horário de uma biblioteca. Para sustentar a proposta, informa que, em uma consulta com 200 usuários, 140 disseram só poder frequentá-la à noite. O recurso argumentativo utilizado é:', ['O ataque pessoal aos funcionários.','A descrição de uma experiência sobrenatural.','A repetição de uma ordem sem justificativa.','A criação de uma comparação poética.','O emprego de um dado quantitativo pertinente à proposta.'],4,'O dado 140 de 200 usuários sustenta a demanda por atendimento noturno. É evidência quantitativa daquela consulta, não prova de que toda a população tenha o mesmo horário disponível.'),
 q('Funções da linguagem','Em um cartaz fictício de coleta seletiva está escrito: “Separe o papel limpo e seco. Entregue no ponto de coleta do bairro.” Considerando o objetivo do cartaz, predomina a função:', ['Emotiva, centrada nos sentimentos de quem escreve.','Conativa, voltada a orientar a ação do destinatário.','Metalinguística, voltada a explicar o próprio código linguístico.','Fática, voltada apenas a testar o canal.','Poética, voltada principalmente à sonoridade das palavras.'],1,'Os verbos no imperativo orientam o leitor a realizar ações. Por isso predomina a função conativa ou apelativa, embora o texto também transmita informação.')
 ]},
 { id:'matematica', nome:'Matemática — ENEM', materia:'matematica', questoes:[
 q('Porcentagem','Um curso custa R$ 250,00. Uma campanha oferece desconto de 20% e, sobre o preço já reduzido, mais 10% para pagamento à vista. Qual é o preço final?', ['R$ 150,00','R$ 175,00','R$ 180,00','R$ 200,00','R$ 225,00'],2,'Após o primeiro desconto: 250 × 0,80 = 200. O segundo é aplicado a 200: 200 × 0,90 = 180. Os percentuais sucessivos não se somam diretamente; o desconto total é de 28%.'),
 q('Escala','Em um mapa de escala 1:50 000, um trecho reto de estrada mede 6 cm. Qual é o comprimento real desse trecho?', ['0,3 km','3 km','30 km','300 km','3 000 km'],1,'Cada centímetro representa 50 000 cm. Logo, 6 × 50 000 = 300 000 cm = 3 000 m = 3 km. É necessário converter centímetros em quilômetros.'),
 q('Estatística','Uma equipe registrou as seguintes durações, em minutos, de sete viagens: 12, 15, 15, 18, 20, 25 e 70. Para representar o valor central sem a forte influência da viagem de 70 minutos, usa a mediana. Qual é essa mediana?', ['15 minutos','20 minutos','25 minutos','18 minutos','70 minutos'],3,'Os sete valores já estão em ordem. A mediana é o quarto valor, 18. A média seria 175/7 = 25, mais afetada pelo valor extremo de 70.'),
 q('Probabilidade','Uma caixa contém 3 fichas azuis e 2 vermelhas, indistinguíveis pelo tato. Duas fichas são retiradas ao acaso, sem reposição. Qual é a probabilidade de ambas serem azuis?', ['3/10','9/25','2/5','3/5','1/5'],0,'A chance de azul na primeira retirada é 3/5. Restam 2 azuis entre 4 fichas: 2/4. O produto é (3/5) × (2/4) = 3/10. Sem reposição, as probabilidades mudam.'),
 q('Função afim','Uma empresa cobra R$ 12,00 de taxa fixa mais R$ 3,00 por quilômetro percorrido. Uma entrega custou R$ 57,00, sem outras cobranças. Qual foi a distância percorrida?', ['12 km','19 km','21 km','23 km','15 km'],4,'O modelo é C = 12 + 3d. Para C = 57: 3d = 57 − 12 = 45, portanto d = 15 km. Dividir 57 por 3 ignoraria a taxa fixa.')
 ]},
 { id:'biologia', nome:'Biologia — ENEM', materia:'biologia', questoes:[
 q('Ecologia','Um lago recebe excesso de nutrientes de esgoto. Após intensa proliferação de algas, parte delas morre e é decomposta. A morte de peixes pode ocorrer porque a decomposição aeróbia:', ['Produz oxigênio em quantidade ilimitada.','Consome oxigênio dissolvido necessário aos peixes.','Transforma diretamente todos os peixes em algas.','Impede a entrada de qualquer nutriente no lago.','Elimina a respiração dos microrganismos.'],1,'O enriquecimento por nutrientes favorece a eutrofização. A decomposição aeróbia da matéria orgânica consome oxigênio dissolvido, podendo causar hipóxia e morte de peixes. Decompor não equivale a realizar fotossíntese.'),
 q('Evolução','Em uma população bacteriana, algumas bactérias já possuem uma variante hereditária de resistência. Após exposição a um antibiótico, aumenta a proporção de resistentes. A explicação evolutiva é:', ['O antibiótico ensinou cada bactéria a resistir.','Todas as bactérias sofreram a mesma mutação dirigida.','As bactérias sensíveis escolheram mudar seus genes.','As resistentes tiveram maior sobrevivência e reprodução nesse ambiente.','A resistência surgiu porque a população precisava dela.'],3,'A seleção natural favorece variantes hereditárias que já conferem vantagem naquele ambiente. O antibiótico atua como pressão seletiva; o processo não pressupõe aprendizagem ou mutações dirigidas pela necessidade.'),
 q('Genética','Em um modelo mendeliano de dominância completa, A é dominante e a é recessivo. Dois indivíduos heterozigotos Aa têm descendentes. Qual a probabilidade de um descendente apresentar o fenótipo recessivo?', ['25%','50%','75%','100%','0%'],0,'Aa × Aa produz AA, Aa, Aa e aa com probabilidades 1/4, 1/4, 1/4 e 1/4. Apenas aa expressa o fenótipo recessivo, portanto 25%, sob as condições do modelo.'),
 q('Fluxo de energia','Em uma cadeia alimentar, a energia disponível nos produtores é estimada em 10 000 kJ. Supondo transferência de 10% a cada nível trófico, quanta energia chega aos consumidores secundários?', ['10 kJ','1 000 kJ','100 kJ','5 000 kJ','10 000 kJ'],2,'Há duas transferências: produtores → consumidores primários → secundários. Assim, 10 000 × 0,10 × 0,10 = 100 kJ. A eficiência de 10% é uma hipótese do problema, não uma constante universal.'),
 q('Ciclo do carbono','Uma área florestada é desmatada e sua biomassa é queimada. Considerando o carbono que estava armazenado nos tecidos vegetais, qual é uma consequência direta da combustão completa dessa matéria orgânica?', ['Conversão de todo o carbono em oxigênio molecular.','Fixação imediata de todo o carbono no solo.','Retirada obrigatória de CO₂ da atmosfera.','Eliminação do ciclo do carbono.','Liberação de parte do carbono para a atmosfera na forma de CO₂.'],4,'Na combustão completa, o carbono da matéria orgânica é oxidado a CO₂. A perda de vegetação também pode reduzir a fixação futura por fotossíntese, mas a consequência direta solicitada é a emissão pela queima.')
 ]},
 { id:'fisica', nome:'Física — ENEM', materia:'fisica', questoes:[
 q('Energia elétrica','Um chuveiro de 5 500 W é usado por 20 minutos diários durante 30 dias. Considerando potência constante, qual é o consumo nesse período?', ['5,5 kWh','11 kWh','33 kWh','55 kWh','110 kWh'],3,'A potência é 5,5 kW. O tempo total é (20/60) × 30 = 10 h. Energia = potência × tempo = 5,5 × 10 = 55 kWh.'),
 q('Cinemática','Um ônibus percorre 120 km em 2 horas e depois fica parado por 30 minutos. Qual é a velocidade escalar média considerando todo esse intervalo, inclusive a parada?', ['48 km/h','60 km/h','80 km/h','96 km/h','120 km/h'],0,'A distância total é 120 km e o tempo total é 2,5 h. A velocidade escalar média é 120/2,5 = 48 km/h. Usar apenas as duas horas de movimento exclui a parada indevidamente.'),
 q('Calorimetria','Para aquecer 500 g de água de 20 °C a 40 °C, considere calor específico de 4,2 J/(g·°C), sem mudança de fase ou perdas. Qual é a energia necessária?', ['4 200 J','10 500 J','21 000 J','84 000 J','42 000 J'],4,'Q = mcΔT = 500 × 4,2 × (40 − 20) = 42 000 J. A variação de temperatura é 20 °C, não a temperatura final de 40 °C.'),
 q('Circuitos elétricos','Um resistor ôhmico de 20 Ω é ligado a uma fonte ideal de 10 V. Qual é a corrente elétrica que o atravessa?', ['0,2 A','0,5 A','2 A','10 A','200 A'],1,'Pela lei de Ohm, I = U/R = 10/20 = 0,5 A. A resistência e a tensão foram dadas diretamente, sem outros resistores no circuito.'),
 q('Ondulatória','Uma onda periódica propaga-se a 340 m/s com frequência de 170 Hz. Qual é seu comprimento de onda?', ['0,5 m','1 m','2 m','170 m','510 m'],2,'A relação v = λf fornece λ = v/f = 340/170 = 2 m. Frequência e comprimento de onda são grandezas distintas.')
 ]},
 { id:'quimica', nome:'Química — ENEM', materia:'quimica', questoes:[
 q('Soluções','Um laboratório dilui 100 mL de solução de concentração 2,0 mol/L, adicionando água até o volume final de 500 mL. Sem reação ou perda de soluto, a concentração final é:', ['0,04 mol/L','0,20 mol/L','1,0 mol/L','10 mol/L','0,40 mol/L'],4,'A quantidade de soluto permanece constante: C₁V₁ = C₂V₂. Portanto, C₂ = (2,0 × 100)/500 = 0,40 mol/L. O volume final é 500 mL, e não 600 mL.'),
 q('Estequiometria','Na combustão completa do metano, CH₄ + 2 O₂ → CO₂ + 2 H₂O. Para queimar 16 g de CH₄, qual massa de O₂ é necessária? Considere massas molares: CH₄ = 16 g/mol e O₂ = 32 g/mol.', ['16 g','32 g','64 g','96 g','128 g'],2,'16 g de metano correspondem a 1 mol. A equação exige 2 mol de O₂ por mol de metano. A massa necessária é 2 × 32 = 64 g.'),
 q('Acidez','Em uma solução aquosa diluída idealizada, a concentração de H₃O⁺ é 1,0 × 10⁻³ mol/L. Usando pH = −log₁₀[H₃O⁺], qual é o pH?', ['3','7','11','−3','0,001'],0,'log₁₀(10⁻³) = −3. Assim, pH = −(−3) = 3. A solução é ácida; pH não é numericamente igual à concentração.'),
 q('Separação de misturas','Uma amostra contém somente água e areia insolúvel. Para reter a areia e obter a água como filtrado, o procedimento mais direto é:', ['Destilação fracionada.','Decantação seguida de fusão.','Cromatografia gasosa.','Filtração com poros que retenham os grãos de areia.','Eletrólise da água.'],3,'A filtração separa um sólido insolúvel de um líquido quando os poros retêm o sólido. A pergunta pede a água como filtrado, não uma separação de líquidos miscíveis nem uma transformação química.'),
 q('Eletroquímica','Em uma pilha, um eletrodo de zinco sofre a transformação Zn(s) → Zn²⁺(aq) + 2 e⁻. Nesse eletrodo ocorre:', ['Redução, com ganho de elétrons.','Oxidação, com perda de elétrons.','Neutralização, com formação obrigatória de água.','Fusão, sem alteração química.','Precipitação, com retirada de íons da solução.'],1,'O zinco metálico perde dois elétrons e forma Zn²⁺. Perda de elétrons caracteriza oxidação, que ocorre no ânodo da pilha. Redução é ganho de elétrons.')
 ]},
 { id:'humanas', nome:'Ciências Humanas — ENEM', materia:'humanas', questoes:[
 q('Urbanização','Após substituir solo permeável por asfalto, um bairro apresenta maior escoamento superficial durante chuvas de mesma intensidade e duração. Qual processo explica diretamente essa mudança?', ['Aumento da infiltração no solo.','Desaparecimento da gravidade.','Redução da infiltração e maior encaminhamento da água pela superfície.','Transformação da chuva em água subterrânea instantaneamente.','Eliminação da necessidade de drenagem.'],2,'A impermeabilização reduz a infiltração local e aumenta a parcela de chuva que escoa pela superfície. Isso pode sobrecarregar a drenagem, dependendo de sua capacidade e de outros fatores.'),
 q('Cartografia','Em um mapa orientado com o norte para cima, a escola está à direita da praça, sobre a mesma linha horizontal. Em que direção a escola está em relação à praça?', ['Norte','Sul','Oeste','Nordeste','Leste'],4,'Com norte para cima, leste corresponde à direita e oeste à esquerda. Como os pontos estão na mesma linha horizontal, não há componente norte ou sul para indicar nordeste ou sudeste.'),
 q('Demografia','Uma população apresenta queda duradoura da fecundidade e aumento da sobrevivência nas idades adultas e avançadas. Mantidos esses processos, qual mudança na estrutura etária é esperada?', ['Aumento da participação relativa de idosos.','Aumento obrigatório da proporção de crianças.','Desaparecimento imediato da população adulta.','Crescimento infinito da população total.','Impossibilidade de envelhecimento populacional.'],0,'Menos nascimentos reduzem a renovação pela base, e maior sobrevivência amplia a presença de pessoas em idades elevadas. O resultado esperado é envelhecimento da estrutura etária; isso não implica crescimento populacional infinito.'),
 q('Trabalho e industrialização','Em uma fábrica, cada trabalhador executa repetidamente uma etapa específica, enquanto máquinas e supervisores coordenam o ritmo da produção. Em comparação com um artesão que domina a fabricação integral, essa organização se caracteriza pela:', ['Eliminação de toda forma de hierarquia.','Fragmentação das tarefas e maior controle do processo de trabalho.','Ausência de especialização.','Substituição da produção por coleta de recursos naturais.','Autonomia completa de cada trabalhador sobre o ritmo coletivo.'],1,'A divisão em etapas fragmenta o trabalho e permite coordenar seu ritmo. O trabalhador deixa de realizar necessariamente o produto inteiro. Isso não elimina hierarquia nem garante autonomia completa.'),
 q('Patrimônio cultural','Uma comunidade registra relatos de mestres locais sobre cantos transmitidos oralmente entre gerações. Ao valorizar essa prática, a iniciativa reconhece como patrimônio:', ['Somente construções feitas de pedra.','Apenas objetos com elevado preço de venda.','Exclusivamente documentos escritos pelo Estado.','Saberes e expressões culturais que integram a memória coletiva.','Somente costumes que nunca sofreram transformações.'],3,'Patrimônio cultural também abrange saberes, práticas e expressões transmitidos socialmente. A oralidade pode preservar memória e identidade; o reconhecimento não depende de preço comercial ou de absoluta imutabilidade.')
 ]}
];
